data: check for missing or unreferenced svg files
Oh shell-fu, don't leave me now.

In data/, check for any svg files that are listed as Layout but don't exist.
In data/layout, check for any existing file that's not listed in the tablet
files.

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
Reviewed-by: Jason Gerecke <jason.gerecke@wacom.com>

diff --git a/data/Makefile.am b/data/Makefile.am
--- a/data/Makefile.am
+++ b/data/Makefile.am
@@ -1,5 +1,6 @@
 libwacomtabletdir = $(datadir)/libwacom
-dist_libwacomtablet_DATA =  $(shell find $(top_srcdir)/data -name "*.tablet" -printf "%P\n")
+tablet_files = $(shell find $(top_srcdir)/data -name "*.tablet" -printf "%P\n")
+dist_libwacomtablet_DATA =  $(tablet_files)
 
 libwacomstylusdir = $(datadir)/libwacom
 dist_libwacomstylus_DATA =  $(shell find $(top_srcdir)/data -name "*.stylus" -printf "%P\n")
@@ -7,3 +8,12 @@ dist_libwacomstylus_DATA =  $(shell find $(top_srcdir)/data -name "*.stylus" -pr
 EXTRA_DIST = wacom.example
 
 SUBDIRS = layouts
+
+check:
+	@for file in $(tablet_files); do \
+		svg=`$(GREP) 'Layout=' "$(top_srcdir)/data/$$file" | $(SED) -e "s/Layout=//"`; \
+		test -z "$$svg" || \
+		test -e "$(top_srcdir)/data/layouts/$$svg" || ( \
+			echo "ERROR: File $$file references nonexistent $$svg" && test); \
+		rc="$$(($$rc + $$?))"; \
+	done && test 0 -eq $$rc
diff --git a/data/layouts/Makefile.am b/data/layouts/Makefile.am
--- a/data/layouts/Makefile.am
+++ b/data/layouts/Makefile.am
@@ -1,4 +1,12 @@
 libwacomlayoutsdir = $(datadir)/libwacom/layouts
-dist_libwacomlayouts_DATA =  $(shell find $(top_srcdir)/data/layouts -name "*.svg" -printf "%P\n")
+layouts = $(shell find $(top_srcdir)/data/layouts -name "*.svg" -printf "%P\n")
+dist_libwacomlayouts_DATA =  $(layouts)
 
 EXTRA_DIST = README
+
+check:
+	@for file in $(layouts); do \
+		$(GREP) -q "$$file" $(top_srcdir)/data/*.tablet || (\
+			echo "ERROR: Layout $$file is not referenced" && test); \
+		rc="$$(($$rc + $$?))"; \
+	done && test 0 -eq $$rc
