data: add makefile hook to verify all files are in git
Use a trick to verify git is there. configure.ac falls back to /usr/bin/false
if git is missing from the path, so any git command will fail. Since we check
whether we're in a git directory first (to handle tarballs) this will fail
with /usr/bin/false and that code-path is not met.

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
Reviewed-by: Jason Gerecke <jason.gerecke@wacom.com>

diff --git a/data/Makefile.am b/data/Makefile.am
--- a/data/Makefile.am
+++ b/data/Makefile.am
@@ -3,7 +3,8 @@ tablet_files = $(shell find $(top_srcdir)/data -name "*.tablet" -printf "%P\n")
 dist_libwacomtablet_DATA =  $(tablet_files)
 
 libwacomstylusdir = $(datadir)/libwacom
-dist_libwacomstylus_DATA =  $(shell find $(top_srcdir)/data -name "*.stylus" -printf "%P\n")
+stylus_files = $(shell find $(top_srcdir)/data -name "*.stylus" -printf "%P\n")
+dist_libwacomstylus_DATA = $(stylus_files)
 
 EXTRA_DIST = wacom.example
 
@@ -16,4 +17,12 @@ check:
 		test -e "$(top_srcdir)/data/layouts/$$svg" || ( \
 			echo "ERROR: File $$file references nonexistent $$svg" && test); \
 		rc="$$(($$rc + $$?))"; \
-	done && test 0 -eq $$rc
+	done && test 0 -eq $$rc;
+	@(export GIT_DIR="$(top_srcdir)/.git"; \
+	 if $(GIT) ls-files >& /dev/null; then \
+		for file in $(tablet_files) $(stylus_files); do \
+			$(GIT) ls-files --error-unmatch "data/$$file" &> /dev/null || ( \
+			echo "ERROR: File $$file is not in git" && test); \
+		rc="$$(($$rc + $$?))"; \
+		done && test 0 -eq $$rc; \
+	fi)
